### ISSUE TITLE
在安卓手机下会卡帧

### ISSUE THREAD

**Issue by cole-yeah** [NewNewKing/SmallRomance#4]
uc浏览器，iOS下不会，安卓7的版本
是渲染方式不同吗

**Comment by NewNewKing** [comment]
@cole-yeah  渲染方式是相同的 目前在性能方面，我的能力有限，暂时做到了我能做的。
建议减少烟花炸裂后粒子数（同时减少烟花半径，会好看一点）
文字减少字体大小，或者增大gap都会减少卡顿。

**Comment by cole-yeah** [comment]
@NewNewKing 好的，谢谢。只是问一下
