### ISSUE TITLE
小白求助啊

### ISSUE THREAD

**Issue by figutive** [NewNewKing/SmallRomance#9]
一直显示在loading... 请问是什么情况
看了审查元素没有问题啊，也有dist文件

**Comment by figutive** [comment]
按照说明的步骤弄完后，请问是直接丢到FTP上吗？服务器是阿里云的

**Comment by NewNewKing** [comment]
dist文件里面的内容才是构建之后的内容， 直接将dist文件的内容放上去就可以了

**Comment by figutive** [comment]
万分感谢，已经弄好了
